version: '3.8'

services:
  realsense_ros_docker:
    image: realsense-ros2-humble:latest
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/workspace
    command: /bin/bash -c "cd /workspace && source /opt/ros/humble/setup.bash && ros2 launch realsense2_camera rs_launch.py"
    #privileged: true
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
      - /dev/video4:/dev/video4
      - /dev/video5:/dev/video5
      - /dev/media0:/dev/media0
      - /dev/media1:/dev/media1
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
